#!/usr/bin/env bash

# This script must be sourced or used as eval "$(/path/to/kiro-sessionizer)"
# to change the directory of the parent shell.
# However, for a simple implementation that works as a command:

if [ $# -eq 0 ]; then
    COMMAND=$(kiro_sessionizer)
    if [ -n "$COMMAND" ]; then
        eval "$COMMAND"
    fi
else
    # Check if the subcommand might return a command to eval (jump, search or continue)
    case "$1" in
        jump|search|continue)
            COMMAND=$(kiro_sessionizer "$@")
            if [ -z "$COMMAND" ]; then
                : # Do nothing
            elif [[ "$COMMAND" == cd\ * ]] || [[ "$COMMAND" == tmux\ * ]]; then
                eval "$COMMAND"
            else
                echo "$COMMAND"
            fi
            ;;
        *)
            kiro_sessionizer "$@"
            ;;
    esac
fi
